### ISSUE TITLE
Favicon outdated

### ISSUE THREAD

**Issue by printer83mph** [phyff/phyff#15]
## We're still using the 2019 style for the favicon!

I suggest we base a new one off the current social media icon.

![profile_pic@120px](https://user-images.githubusercontent.com/22186744/72656488-cf5e4f80-399b-11ea-8379-db3c22cc8e58.png)

Of course it would have to be 16px but it shouldn't be that hard to do. Leo - I'm tagging you in case you want to do this, let me know if you're working on it.

**Comment by willybh11** [comment]
Done.
