### ISSUE TITLE
Little design stuff

### ISSUE THREAD

**Issue by printer83mph** [phyff/phyff#19]
Weird design decisions and such.

* Right side of attend section goes past line
* Size of titles is inconsistent
* Button styling is inconsistent

These are lower-priority issues but an issues nonetheless.

**Comment by hexidian** [comment]
I fixed the issue with the attend grid not being lined up by moving the sign-up button above the grid

**Comment by printer83mph** [comment]
Did you modify the scss or just the html

**Comment by printer83mph** [comment]
Could you do any future changes in a branch off scss-update? That way we don't have to do crazy diff stuff when we merge it in
