### ISSUE TITLE
Finish learn section

### ISSUE THREAD

**Issue by printer83mph** [phyff/phyff#5]
needs to be done this week

**Comment by l-u-n-c-h-b-o-x** [comment]
whgat is a computer

**Comment by printer83mph** [comment]
i donnot know

**Comment by l-u-n-c-h-b-o-x** [comment]
kind BiG problem, our site gets blocked by some browser's filters for a "certificate error"

like those this site is stealing your info kinda ish

**Comment by printer83mph** [comment]
hmm seems like a domain/cname problem god damn it i thought i fixed it

i think theres a problem w/ `www.phyff.com` vs just `phyff.com`

**Comment by l-u-n-c-h-b-o-x** [comment]
typing https://www.phyff.com/ nets the same error in edge

**Comment by l-u-n-c-h-b-o-x** [comment]
ima try opera/firefox

**Comment by l-u-n-c-h-b-o-x** [comment]
yeah in all three of those browsers typing in any form of the address gives you a certificate error, you can only bypass the warning in opera

**Comment by printer83mph** [comment]
hmm with or without https://

**Comment by printer83mph** [comment]
i think its that once youve visited https://www.phyff.com then everything redirects to that bcus cache or something

**Comment by printer83mph** [comment]
typing either phyff.com or www.phyff.com works on a fresh browser

but we should still fix this tho

**Comment by l-u-n-c-h-b-o-x** [comment]
with. any form

this a moderate issue in normal browsers but I feel like it becomes a big issue if it happens for visitors coming through browsers integrated into Instagram/reddit/twitter/facebook since that's generally how social media handles links on mobile nowadays

**Comment by l-u-n-c-h-b-o-x** [comment]
and if it's a cache issue then that's still bad because potential submitters may revisit the site

**Comment by printer83mph** [comment]
https://github.com/phyff/phyff/issues/7

**Comment by printer83mph** [comment]
Can you still finish up this section

**Comment by l-u-n-c-h-b-o-x** [comment]
Ye on it rn
