### ISSUE TITLE
Background not fixed in place on mobile

### ISSUE THREAD

**Issue by printer83mph** [phyff/phyff#9]
Bug: background not fixed on mobile

_Originally posted by @printer83mph in https://github.com/phyff/phyff/issues/4#issuecomment-459214933_

**Comment by printer83mph** [comment]
Current ideas:
* Static background on mobile, could be too stretched out
* Separate background file for mobile devices, that way we're not wasting bandwidth/image size
* ~Scroll based script to update background positions~ (check 13bb6b77a8042ca02dcfee5472a75450912c630a)

**Comment by l-u-n-c-h-b-o-x** [comment]
Honestly I barely know how to do this but I'll see

**Comment by robertmay2003** [comment]
This is not an issue with mobile browsers, it is an issue with screen width. If you make the screen narrow on desktop the background disappears as well. Gruh

**Comment by printer83mph** [comment]
It is complete
